name: Build XIOO firmware
on: [push]

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0

    - name: Install AVR board
      run: arduino-cli core update-index && arduino-cli core install arduino:avr

    - name: Install libraries
      run: arduino-cli lib install FastLED "Adafruit MPR121"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile
      run: arduino-cli compile --fqbn arduino:avr:nano ./XIIO_v2_firmware.ino
